/* 
  *   Speech.java generated by speechmod 
 */   

package Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

	FULLSCREEN("[SPEECH][FULLS]",2000),
	NORMALSCREEN("[SPEECH][NORMALS]",2000),
	SLIDEDOWN("[SPEECH][SLIDED]",7000),
	SLIDEUP("[SPEECH][SLIDEUP]",7000),
	VOLUMEUP("[SPEECH][VOLUMEU]",5000),
	VOLUMEDOWN("[SPEECH][VOLUMED]",5000),

	// HELP("[SPEECH][HELP]"),
    // HELP_OPERACOES("[SPEECH][HELP][OPERACOES]"),
    // HELP_GESTOS("[SPEECH][HELP][GESTOS]"),
    // HELP_TODAS("[SPEECH][HELP][TODAS]"),

	;


private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
